### PR TITLE
Fix types.

### PR DESCRIPTION
**Pull request by itsayushch**
Fixed types for `.setFontSize` method. The method accepts only number however it should accept a string too. For example `"26px"`.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
This should be changed to only a string. Looking at how we use this if you passed just a number in it would be used without a unit specifier like px.

**Review by OmgImAlexis — CHANGES_REQUESTED** [review]
What are you doing?

**Comment by OmgImAlexis** [comment]
This should fix a single issue. I'm not really sure why you pushed "test" to this.

**Comment by itsayushch** [comment]
> 
> 
> What are you doing?

Ahh, it was for my personal testing. I was not aware that it would come in the PR.

**Pull request closed without merging**
